/*
GroupDocs.Translation SDK

Testing FileAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package groupdocs_translation_cloud

import (
	"context"
	openapiclient "github.com/groupdocs-translation-cloud/groupdocs-translation-cloud-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"os"
	"testing"
)

func Test_groupdocs_translation_cloud_FileAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration(os.Getenv("GDT_ClientId"), os.Getenv("GDT_ClientSecret"))
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FileAPIService FileUploadPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FileAPI.FileUploadPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
